language: go
go:
  - 1.3.3
  - 1.4.3
  - 1.5.4
  - 1.6.2
  - 1.7
  - tip

install:
  - go get -v -t -d github.com/icedream/go-footballdata/...

script:
  - go test -v github.com/icedream/go-footballdata/...